### PR TITLE
Update tests to run faster

### PR DESCRIPTION
**Pull request by simedroniraluca**

### CODE REVIEW

**Review by ruxandra-valcu — APPROVED** [review]
Looks good. How much does this speed up things, btw?

**Comment by simedroniraluca** [comment]
> Looks good. How much does this speed up things, btw?

The modifications have reduced the test runtime from approximately 33 minutes to 19m 47s on my MacBook Pro (2.8 GHz Quad-Core Intel Core i7). We are close to the upper limit of the accepted 20 minutes, but currently, no tests are being ignored. In the future, some tests might be skipped because certain functions are very similar, and tests for one function can cover others. Examples of such functions are `create_default_noise_masks_oceanstream`, `create_noise_masks_rapidkrill`, and `create_noise_masks_oceanstream`. (The tests for shoal detection are still the slowest.)

**Review by mihaiboldeanu — APPROVED** [review]

**Comment by simedroniraluca** [comment]
> > Looks good. How much does this speed up things, btw?
> 
> The modifications have reduced the test runtime from approximately 33 minutes to 19m 47s on my MacBook Pro (2.8 GHz Quad-Core Intel Core i7). We are close to the upper limit of the accepted 20 minutes, but currently, no tests are being ignored. In the future, some tests might be skipped because certain functions are very similar, and tests for one function can cover others. Examples of such functions are `create_default_noise_masks_oceanstream`, `create_noise_masks_rapidkrill`, and `create_noise_masks_oceanstream`. (The tests for shoal detection are still the slowest.)

On GitHub, the tests take 20m 25s to run, exceeding the upper limit of 20m. I will leave some of them ignored.

**Review by ruxandra-valcu — APPROVED** [review]
Approved

**Pull request merged**
